### ISSUE TITLE
edgegrid send uses throw inside an async method, pattern has no safe way to catch the error.

### ISSUE THREAD

**Issue by gmcnaught** [akamai-open/AkamaiOPEN-edgegrid-node#12] opened 2016-02-25 21:54 UTC
https://github.com/akamai-open/AkamaiOPEN-edgegrid-node/blob/master/src/api.js#L68-L72

The 'best practice' in an async method is to return an error object as the first item of the callback if an error occurred, or null if otherwise.  It appears the way this throw is implemented, it cannot be caught.

**Comment by ktyacke** [comment] 2016-04-20 17:53
Hey Grant,
Sorry for the ridiculous delay on response to this issue. The reason this was implemented inline with a throw is that it was intended to end execution and output useful data to the console/log/etc should this specific error be encountered. That being said, you make a valid point, and I could see how being able to receive the error info in the callback might be useful for devs using the library. Any thoughts on setting a default output to notify the user that the error occurred while also returning the error to the callback? Would welcome a PR for this one =]

**Comment by erdarun** [comment] 2016-07-13 13:22
Hi ktyacke,

I have fixed the code ./src/api.js, 
Tried PR by creating new branch to master but access denied for my user to create new branch.

I have removed error thrown and passed error to callback which makes easier for developer who consumes API to handle error. Also node app will not end the execution. Think in our case we are hitting security monitor Akamai API's if due to any intermittent network issues not able to reach Akamai host server then our node app will be shutdown which requires restart every time not advisable for every error from Akamai.

Refer below code snippet,

EdgeGrid.prototype.send = function(callback) {
  request(this.request, function(error, response, body) {
    if (error) {
      // Removed throwing error and returned the error to callback;
      return callback(error);
    }

    if (helpers.isRedirect(response.statusCode)) {
      this._handleRedirect(response, callback);
      return;
    }

    // Set error as null for success scenarios to callback
    callback(null, body, response);
  }.bind(this));
};

Thanks.

**Comment by ktyacke** [comment] 2016-08-26 13:09
Hey erdarun,
You should be able to submit a PR by forking the repo, then submitting the PR from the new fork. https://help.github.com/articles/creating-a-pull-request-from-a-fork/ 

If you want to give that a shot, I'll review and merge in.

Thanks,

Kyle

**Comment by ktyacke** [comment] 2016-09-28 19:10
Fixed in PR #21

**Closed by ktyacke** 2016-09-28 19:10 UTC
